### ISSUE TITLE
Pull based on partial array match

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy#275]
I have the following specification:

```
User.extend

  fields:
    pushNotificationTokens:
      type: "array"
      nested:
        name: "PushNotificationToken"
        fields:
          token:
            type: "string"
            default: -> uuid()
          createdAt:
            type: "date"
            default: -> new Date()
      default: -> []
```

If someone submits a request with a token, I'd like to remove it from the list of valid tokens so it can't be used again.

Unfortunately, `user.pull("pushNotificationTokens", {token: "value of valid token"})` doesn't appear to remove the token. Initially I thought the array had to be an exact match, but looking at the Mongo $pull docs which I assume this is modeled off of, I now don't get that impression.

Is there anything obviously wrong with my query, and is there some way I can get a look at the underlying Mongo query to figure out what might be going wrong?

Thanks.
